[package]
name = "staticlib1"
version = "0.1.0"
edition = "2021"
authors = ["yashwanth singh<yashwanthsinghm@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
